### ISSUE TITLE
Should be able to fix template resolution value throughout process

### ISSUE THREAD

**Issue by Luke-Rogers** [mog13/Splain#55]
When a template is processed, I to be able to say that once a template is resolved, if that template is met again the first resolution value is used. This will mean that the context does not mess up when using the referencing the result multiple times throughout the text.

**Comment by mog13** [comment]
Great idea! this would be super useful!

To further add to this (after in person discussion):

It could work with entries having optional contexts. Say in the choice of [dusk, dawn, midnight, late, early, sunset, sunrise] then sunset might have the context night. This context could then be used to filter future choices. My opinion is that in future choices this context should only come in to play if any of the potential choices contain a context the same as the current running contexts. for instance as above might add 'night' to a running context then further in the process a choice of [spring, summer, autumn. winter] is presented. if none of them have a night context than one at random is chosen, furthermore if the chosen one has a context of its own it would be added to the running contexts. This means future choices would check to match any contexts with new ones being added only when a like context isnt selectable.

**Comment by Luke-Rogers** [comment]
Going to break this out into another task #56
